import { readFile } from "node:fs/promises";

const files = [
  "index.html",
  "styles.css",
  "themes.css",
  "app.js",
  "internal/certificates.js",
  "internal/certificate-fixtures.js",
  "api/card-image.js",
  "api/cards.js",
  "api/catalog.js",
  "api/capabilities.js",
  "api/health.js",
  "api/sales.js",
  "api/graded-valuation.js",
  "api/fx.js",
  "api/vision.js",
  "api/price-sync.js",
  "api/maintenance.js",
  "lib/advisor.js",
  "lib/action-center.js",
  "lib/catalog-db.js",
  "lib/collection-organization.js",
  "lib/core.js",
  "lib/domain.js",
  "lib/env.js",
  "lib/gateway-models.js",
  "lib/grading-pilot-api.js",
  "lib/grading.js",
  "lib/grading-capture.js",
  "lib/grading-economics.js",
  "lib/grading-v3.js",
  "lib/grading-dataset-v3.js",
  "lib/grading-lifecycle.js",
  "lib/image-source.js",
  "lib/notification-delivery.js",
  "lib/identity.js",
  "lib/portfolio.js",
  "lib/graded-valuation.js",
  "lib/psa-calibration.js",
  "lib/psa-pilot.js",
  "lib/software-modes.js",
  "lib/pricing.js",
  "lib/fx.js",
  "lib/supabase-data.js",
  "lib/native-runtime.js",
  "scripts/verify-native-artifact.mjs",
  "lib/vision.js",
  "lib/vision-evaluation.js",
  "lib/providers/base.js",
  "lib/providers/index.js",
  "lib/providers/alt.js",
  "lib/providers/cardladder.js",
  "lib/providers/justtcg.js",
  "lib/providers/pkmnprices.js",
  "lib/pkmnprices-readiness.js",
  "lib/providers/tcgdex.js",
  "playwright.config.js",
  "scripts/benchmark-grading-models.mjs",
  "scripts/benchmark-collection-organization.mjs",
  "scripts/build-psa-pilot.mjs",
  "scripts/publish-psa-calibration.mjs",
  "scripts/evaluate-vision.mjs",
  "scripts/evaluate-grading-shadow-v3.mjs",
  "scripts/evaluate-identity-benchmark.mjs",
  "scripts/export-grading-dataset-v3.mjs",
  "scripts/serve.mjs",
  "scripts/verify-certificate-exclusion.mjs",
  "scripts/train-psa-calibration.mjs",
  "scripts/verify-pkmnprices.mjs",
  "scripts/verify-action-center.mjs",
  "scripts/verify-identity-migration.mjs",
  "scripts/verify-grading-lifecycle.mjs",
  "scripts/verify-collection-organization.mjs",
  "scripts/verify-software-modes.mjs",
  "tests/advisor.test.js",
  "tests/action-center.test.js",
  "tests/browser/ui-regression.spec.js",
  "tests/catalog.test.js",
  "tests/collection-organization.test.js",
  "tests/capture-precision.test.js",
  "tests/certificate-workflows.test.js",
  "tests/browser/certificate-workflows.spec.js",
  "tests/browser/shipping-certificate-exclusion.spec.js",
  "tests/grading-dataset-v3.test.js",
  "tests/grading-pilot.test.js",
  "tests/grading-v3.test.js",
  "tests/grading-lifecycle.test.js",
  "tests/grading.test.js",
  "tests/identity.test.js",
  "tests/detailed-printing.test.js",
  "tests/maintenance.test.js",
  "tests/notification-delivery.test.js",
  "tests/psa-calibration.test.js",
  "tests/psa-pilot.test.js",
  "tests/pkmnprices-readiness.test.js",
  "tests/graded-valuation.test.js",
  "tests/software-modes.test.js",
  "manifest.webmanifest",
  "sw.js",
];

const failures = [];
for (const file of files) {
  const text = await readFile(new URL(`../${file}`, import.meta.url), "utf8");
  if (/PokÃ|â€”|â€™|ðŸ/.test(text)) failures.push(`${file}: contains mojibake`);
  if (/console\.log\(/.test(text))
    failures.push(`${file}: contains console.log`);
}
if (failures.length) {
  console.error(failures.join("\n"));
  process.exit(1);
}
console.info(`Linted ${files.length} source files.`);
